include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
  enable-experiment:
    - macros

linter:
  rules:
    - combinators_ordering
    - comment_references
    - directives_ordering
    - test_types_in_equals
    - throw_in_finally
