name: mockito
version: 5.4.4
description: >-
  A mock framework inspired by Mockito with APIs for Fakes, Mocks,
  behavior verification, and stubbing.
repository: https://github.com/dart-lang/mockito

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: '>=6.4.1 <7.0.0'
  build: ^2.0.0
  code_builder: ^4.5.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  matcher: ^0.12.15
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^1.0.0
  test_api: '>=0.2.1 <0.8.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  http: ^1.0.0
  lints: ^3.0.0
  package_config: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  _fe_analyzer_shared:
    path: ../dart-sdk/sdk/pkg/_fe_analyzer_shared
  _js_interop_checks:
    path: ../dart-sdk/sdk/pkg/_js_interop_checks
  analyzer:
    path: ../dart-sdk/sdk/pkg/analyzer
  build_integration:
    path: ../dart-sdk/sdk/pkg/build_integration
  compiler:
    path: ../dart-sdk/sdk/pkg/compiler
  dart2wasm:
    path: ../dart-sdk/sdk/pkg/dart2wasm
  dart2js_info:
    path: ../dart-sdk/sdk/pkg/dart2js_info
  dev_compiler:
    path: ../dart-sdk/sdk/pkg/dev_compiler
  front_end:
    path: ../dart-sdk/sdk/pkg/front_end
  frontend_server:
    path: ../dart-sdk/sdk/pkg/frontend_server
  js_ast:
    path: ../dart-sdk/sdk/pkg/js_ast
  js_runtime:
    path: ../dart-sdk/sdk/pkg/js_runtime
  js_shared:
    path: ../dart-sdk/sdk/pkg/js_shared
  kernel:
    path: ../dart-sdk/sdk/pkg/kernel
  meta:
    path: ../dart-sdk/sdk/pkg/meta
  mmap:
    path: ../dart-sdk/sdk/pkg/mmap
  vm:
    path: ../dart-sdk/sdk/pkg/vm
  wasm_builder:
    path: ../dart-sdk/sdk/pkg/wasm_builder


  build_resolvers:
    path: ../build/build_resolvers
